name: Payments Build Workflow
on:
  push:
    # Build everything else via tag.
    tags:
      - "v**"
    # Build on dev as usual.
    branches:
      - 'dev'
# name: Docker Workflow
# on:
#   workflow_call:
    # inputs:
    #   DOCKER_REPO:
    #     required: true
    #     type: string
    # secrets:
    #   DOCKER_USERNAME:
    #     required: true
    #   DOCKER_PASSWORD:
    #     required: true

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Latest Tag
        id: latest_tag
        run: echo ::set-output name=SEMVER::${GITHUB_REF#refs/*/}
      - name: Checkout API Demo
        uses: actions/checkout@v3
        with:
          path: api
      - name: Checkout Dependencies Demo
        uses: actions/checkout@v3
        with:
          repository: ch4dwick/dependencies-demo
          path: deps
          token: ${{ secrets.API_ASSEMBLER_TOKEN}}
      - name: Checkout Core Demo
        uses: actions/checkout@v3
        with:
          repository: ch4dwick/core-demo
          path: core
          token: ${{ secrets.API_ASSEMBLER_TOKEN}}
      - name: Avengers, Assemble!
        id: build_image
        env:
          # ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          # ECR_REPOSITORY: "${{ inputs.ECR_REPO }}"
          # IMAGE_TAG: ${{ inputs.TAG }}
          SEMVER: ${{ inputs.SEMVER }}
        run: |
          SUFFIX=$(echo $SEMVER | awk -F - '{print $NF}')
          docker build -t core:$SEMVER .
        # run: |
        #   SUFFIX=$(echo $SEMVER | awk -F - '{print $NF}')
        #   docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$SEMVER \
        #     -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
        #     -t $ECR_REGISTRY/$ECR_REPOSITORY:$SUFFIX .
        
    